config/routes.rb
Rails.application.routes.draw do
	ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        sessions: 'sessions/sessions',
        registrations: 'sessions/registrations'
      }
  resources :addresses,:bank_accounts, except: [:show]
  resources :carts, only: [:index, :new]
  resources :products, :shipments, only: [:index, :show]
  resources :orders, except: [:edit] do
    get 'detail_pdf', to: 'orders#order_pdf'
  end
  resources :shipments,:tracking_orders, only: [:show]
  resources :seller_signups, only: [:index]
  resources :line_items, :notifications, :otps
  resources :payments

  post "admin/products/add_sub", to: "admin/products#add_sub"
  post "admin/products/variant", to: "admin/products#variant"
  post "admin/products/size_of_product", to: "admin/products#size_of_product"
  root to: "homes#index"
  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req| (req.path.exclude? 'active_storage')}
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	has_many :line_items, dependent: :destroy

	def cart_method(product)
		product.product_type.eql?("national")? "₹40" : "Free"
	end

	def total_charges(items)
		items.joins(:product).where("product.product_type"=>"national").present? ? 40 : "Free"
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_action :authenticate_user!
	before_action :authenticate_user

	def index
		@items = current_user.cart.line_items.all
	end

	def new
		@product = params[:id]
		current_user.cart.line_items.create(quantity: 1, product_id: @product)
		redirect_to products_path
	end
end

app/views/carts/index.html.erb
<div style="display: flex;">	
	<% if @items.count >0 %>
		<div class="container cart_item">
			<% price_total = 0 %> <% item_total = 0 %>
			<% @items.each do |item| %>
		    <div class="row my-4">
		    	<div class="col-sm-3">
		    		<%= image_tag item.product.images.first, size: "200x200" %>
		    	</div>
		    	<div class="col-sm-6">
		    		<%= item.product.product_name %>
		    		<br />
		    		<%= item.product.description%>
		    		<br />
		    		₹<%= item.product.discount_price * item.quantity %>
		    		<s style="color: #9f9191;">₹<%= item.product.price * item.quantity %></s>
		    		<span style= "color: green;">
            <%= item.product.discount.discount_amount if item.product.discount.present? %> % Off </span>
						<% price_total += item.product.discount_price * item.quantity%>
		    	</div>
		    	<div class="col-sm-3">
		    		<strong>Delivery by <%= delivery_date %></strong>
		    		<p><span style="color: green;">Charges</span><%= item.cart.cart_method(item.product) %></p>
		    	</div>
		    </div>
		    <div class="row" style="margin-top: 25px;">
		    	<div class="col-auto">
		    		<div class="btn-group" role="group" aria-label="Basic example">
			      	<%= button_to "-", edit_line_item_path(item),method: :get, class: "btn-sm btn btn-outline-success" %> 
			      	<span style="padding: 0 8px 0 0"><%= item.quantity %></span> 
			      	<% item_total += item.quantity %> 
			      	<%= button_to "+", line_item_path(item), method: :put, class: "btn-sm btn btn-outline-success" %>
						</div>
					</div>
					<div class="col-auto">
						<div class="btn-group" role="group" aria-label="Basic example">
		      		<%= button_to "Remove", line_item_path(item),data: { confirm: "Are you sure?"}, method: :delete, class: "btn btn-outline-success" %>
		      		<%= link_to "Buy", new_order_path(item_id: item.id, method: :get), class: "btn btn-outline-success"%>
		      	</div>
		      </div>
				</div>
			<% end %>
			<br />
			<br />
			<table class="table">
			  <thead>
			  </thead>
			  <tbody>
			    <tr>
			      <td style="border: none">
						</td>
			      <td style="border: none"></td>
			      <td style="border: none">
				      <div class="buy-all">
					      <% if @items.count > 1 %>
					      	<%=link_to "Buy All", new_order_path(item_id: "#{@items.ids}", method: :get), class: "btn btn-outline-success"%>
					      <% else %>
					      	<%=link_to "Buy All", new_order_path(item_id: @items.first.id, method: :get), class: "btn btn-outline-success"%>
					      <% end %>	
					    </div>
				    </td>
			    </tr>
			  </tbody>
			</table> 
		</div>
		<div class="container cart_total">
			<table class="table">
				  <thead>
				    <tr>
				      <th scope="col">PRICE DETAILS </th>
				    </tr>
				  </thead>
				  <tbody>
				    <tr>
				      <td style="border: none">
				      	Price(<%= item_total %> items)
							</td>
				      <td style="border: none">₹<%= "#{price_total}" %></td>
				    </tr>
				    <tr>
				    	<td style="border: none">Delivery Charges
				    	</td>
				    	<td style="border: none">₹<%= current_user.cart.total_charges(@items) %>
				    	</td>
				    </tr>
				    <tr>
				    	<td style="border: none">Total Price:
				    	</td>
				    	<td style="border: none">₹<%=price_total + current_user.cart.total_charges(@items).to_i %>
				    	</td>
				    </tr>
				    <tr>
				      <% if @items.count > 1 %>
				      	<td style="border: none"><%=link_to "Buy All", new_order_path(id: "#{@items.ids}", method: :get), class: "btn btn-outline-success"%></td>
				      <% else %>
				      	<td style="border: none"><%=link_to "Buy All", new_order_path(id: @items.first.id, method: :get), class: "btn btn-outline-success"%></td>
				      <% end %>	
				    </tr>
				  </tbody>
				</table> 
		</div>
	<% else %>
	<div class="container">
		<h1>Add Items To Cart</h1>
		<%= button_to "Go To Home Page", products_path, class: "btn btn-outline-success", method: :get %> 
		<% end %>
	</div>
</div>