config/routes.rb
Rails.application.routes.draw do
	ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        sessions: 'sessions/sessions',
        registrations: 'sessions/registrations'
      }
  resources :addresses,:bank_accounts, except: [:show]
  resources :carts, only: [:index, :new]
  resources :products, :shipments, only: [:index, :show]
  resources :orders, except: [:edit] do
    get 'detail_pdf', to: 'orders#order_pdf'
  end
  resources :shipments,:tracking_orders, only: [:show]
  resources :seller_signups, only: [:index]
  resources :line_items, :notifications, :otps
  resources :payments

  post "admin/products/add_sub", to: "admin/products#add_sub"
  post "admin/products/variant", to: "admin/products#variant"
  post "admin/products/size_of_product", to: "admin/products#size_of_product"
  root to: "homes#index"
  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req| (req.path.exclude? 'active_storage')}
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
	belongs_to :user
	has_many :notifications, as: :notificable
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
	before_action :authenticate_user
	before_action :authenticate_user!, only: [:edit, :index]

	def new
		@value = params[:value].present? ? params[:value] : nil
		 return redirect_to root_path, alert:"Please Login" unless user_signed_in? || @value.present?
		@account = BankAccount.new 
	end

	def create
		return redirect_to seller_signups_path(permit_params) if params[:bank_account][:query].present?
		@account = current_user.bank_accounts.new(permit_params)
		@account.save
		helpers.add_notification(@account, "Bank Account Added To Your Profile")
		redirect_to bank_accounts_path
	end

	def edit
		@account = BankAccount.find_by(id: params[:id])
		return redirect_to root_path, alert: "Account not found" unless @account.present?
	end

	def update
		@account = BankAccount.find_by(id: params[:id])
		return redirect_to root_path, alert: "Account not found" unless @account.present?
		@account.update(permit_params)
		helpers.add_notification(@account, "Bank Account Updated On Your Profile")
		redirect_to bank_accounts_path
	end

	def index
		@accounts = current_user.bank_accounts.all
	end 

	def destroy 
		@account = BankAccount.find_by(id: params[:id])
		return redirect_to root_path, alert: "Account not found" unless @account.present?
		helpers.add_notification(@account, "Bank Account Removed from Your Profile")
		@account.destroy
		redirect_to bank_accounts_path
	end

	private
		def permit_params 
			params.require(:bank_account).permit(:account_no, :ifsc_code, :bank, :branch_name, :city, :user_id)
		end
end

app/views/bank_accounts/edit.html.erb
<div class="container" style="width: 450px;">
	<div class="d-flex justify-content-center form-group">
	 <h1>Update Account</h1>
	</div>

	<div class="d-flex justify-content-center form-group">
	 <%= form_for @account, url_for: bank_account_path(@account), method: :patch, data:{turbo: false}  do |f| %>
		<div class="field ">
				<%= f.label :account_no %><br />
				<%= f.text_field :account_no , class: "form-control" ,autocomplete: "account_no" %><br />
			</div>

			<div class="field ">
				<%= f.label :ifsc_code %><br />
				<%= f.text_area :ifsc_code , class: "form-control" ,autocomplete: "ifsc_code", size: "25x2"%><br />
			</div>

			<div class="field ">
				<%= f.label :bank %><br />
				<%= f.text_area :bank , class: "form-control" ,autocomplete: "bank", size: "25x2"%><br />
			</div>

			<div class="field ">
				<%= f.label :branch_name %><br />
				<%= f.text_area :branch_name , class: "form-control" ,autocomplete: "branch_name", size: "25x2"%><br />
			</div>

			<div class="field ">
				<%= f.label :city %><br />
				<%= f.text_area :city , class: "form-control" ,autocomplete: "city", size: "25x2"%><br />
			</div>

			<div class = "action" >
				<%= f.submit "Update Account" ,class: "btn btn-primary btn-lg btn-block" %>
			</div>

	 <% end %>
	</div>
</div>

app/views/bank_accounts/index.html.erb
<div class="container">  
  <% if @accounts.count > 0 %>
    <%= button_to "ADD", new_bank_account_path, method: :get, class: "btn btn-primary btn-lg" %>
    <br />
    <table class="table">
      <thead>
        <tr>
          <th scope="col">id</th>
          <th scope="col">Account No</th>
          <th scope="col">Ifsc Code</th>
          <th scope="col">Bank</th>
          <th scope="col">Branch</th>
          <th scope="col">City</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td><b><%= account.id %></b></td>
            <td><%= account.account_no %></td>
            <td><%= account.ifsc_code %></td>
            <td><%= account.bank %></td>
            <td><%= account.branch_name %></td>
            <td><%= account.city %></td>
            <td>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= button_to "Remove", bank_account_path(account),data: { confirm: "Are you sure?"}, method: :delete, class: "btn btn-outline-success" %>
              <%= button_to "Edit", edit_bank_account_path(account), method: :get, class: "btn btn-outline-success" %>
            </td>
            </div>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
  <h1>You Have Not Added Any account At</h1>
  <%= button_to "ADD", new_bank_account_path, method: :get, class: "btn btn-primary btn-lg" %>
  <% end %>
</div>

app/views/bank_accounts/new.html.erb
<div class="container" style="width: 450px;">
	<div class="d-flex justify-content-center form-group">
		<h1>Add Account</h1>
	</div>
	<div class="d-flex justify-content-center form-group">
		<%= form_for @account, url_for: bank_accounts_path, method: :post  do |f| %>  
				<%= f.hidden_field :query, :value => @value %>
			<div class="field ">
				<%= f.label :account_no %><br />
				<%= f.text_field :account_no , class: "form-control" ,autocomplete: "account_no" %><br />
			</div>

			<div class="field ">
				<%= f.label :ifsc_code %><br />
				<%= f.text_field :ifsc_code , class: "form-control" ,autocomplete: "ifsc_code", size: "25x2"%><br />
			</div>

			<div class="field ">
				<%= f.label :bank %><br />
				<%= f.text_field :bank , class: "form-control" ,autocomplete: "bank", size: "25x2"%><br />
			</div>

			<div class="field ">
				<%= f.label :branch_name %><br />
				<%= f.text_field :branch_name , class: "form-control" ,autocomplete: "branch_name", size: "25x2"%><br />
			</div>

			<div class="field ">
				<%= f.label :city %><br />
				<%= f.text_field :city , class: "form-control" ,autocomplete: "city", size: "25x2"%><br />
			</div>

			<div class = "action" >
				<%= f.submit "Add Account" ,class: "btn btn-primary btn-lg btn-block" %>
			</div>
		<% end %>
	</div>
</div>