config/routes.rb
Rails.application.routes.draw do
	ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        sessions: 'sessions/sessions',
        registrations: 'sessions/registrations'
      }
  resources :addresses,:bank_accounts, except: [:show]
  resources :carts, only: [:index, :new]
  resources :products, :shipments, only: [:index, :show]
  resources :orders, except: [:edit] do
    get 'detail_pdf', to: 'orders#order_pdf'
  end
  resources :shipments,:tracking_orders, only: [:show]
  resources :seller_signups, only: [:index]
  resources :line_items, :notifications, :otps
  resources :payments

  post "admin/products/add_sub", to: "admin/products#add_sub"
  post "admin/products/variant", to: "admin/products#variant"
  post "admin/products/size_of_product", to: "admin/products#size_of_product"
  root to: "homes#index"
  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req| (req.path.exclude? 'active_storage')}
end

app/models/product.rb
class Product < ApplicationRecord
	paginates_per 5
	include ApplicationHelper
	has_many :product_colors, dependent: :destroy
	has_many_attached :images, dependent: :destroy
	accepts_nested_attributes_for :product_colors, allow_destroy: true
	validates :stock, presence: true, comparison: {greater_than_or_equal_to: 0}
	has_many :line_items, dependent: :destroy
	has_many :order_items, dependent: :destroy
	has_and_belongs_to_many :offer_types, dependent: :destroy
	has_many :sizes ,dependent: :destroy
	has_many :product_sizes,through: :sizes
	accepts_nested_attributes_for :sizes, allow_destroy: true
	belongs_to :user
	belongs_to :category
	belongs_to :sub_category
	belongs_to :variant
	validates :product_name, :price, :description, presence: true
	enum :product_type,[:national, :personal]
	has_one :discount, dependent: :destroy
	has_many :notifications, as: :notificable
	after_create :notification_method
	after_update :notification_update
	has_and_belongs_to_many :orders, dependent: :destroy

	private
		def notification_method
			add_notification(self, "Your Product Created")
		end

		def notification_update
			add_notification(self, "Your Product Updated")
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :check, only: [:edit, :destroy, :new]
	before_action :authenticate_user
	def index
		products = params[:value].present? ? Product.includes(:category).where("categories.categories_type" => params[:value]) : Product.all
		@products = products.page params[:page] 
	end

	def show
		@product = Product.find_by(id: params[:id])
		return redirect_to root_path, alert: "Product not found" unless @product.present?
		@charges = @product.product_type.eql?("national")? 40 : "Free"
	end
end

app/views/products/index.html.erb
<div class="row" id="card-container">
  <% @products.each do |product| %>
   <div class="card mx-2 my-2" style="width: 22rem;">
      <%= link_to product_path(product) do %>  
        <%= image_tag product.images.first, size: "200x200",class: "card-img-top" %>
      <% end  %>
      <a href='products/<%="#{product.id}"%>' class= "a_product">
        <div class="card-body">  
          <h5 class="card-title">
            <%= "#{product.product_name}"%>
          </h5>
          <p class="card-text">
            <%= "#{product.description.truncate(35)}" %>
          </p>
          <h6>
            ₹<%="#{product.price}" %>
          </h6>
          <%if user_signed_in? && product.line_items.find_by(cart_id: current_user.cart.id).present? %> 
            <%= link_to "GoToCart", carts_path,class: "btn btn-secondary btn-lg btn-block" %>
          <% else %>  
            <% if product.stock == 0 %>
              <%= link_to "AddToCart", root_path,class: "btn btn-secondary btn-lg btn-block" %>
            <% else %>
              <%= link_to "AddToCart", new_cart_path(id: product.id),class: "btn btn-primary btn-lg btn-block" %>
            <% end %>
          <% end %> 
        </div>
      </a>
    </div>
  <% end %>
</div>
<%= paginate @products , theme: 'bootstrap-5', pagination_class: "pagination-sm flex-wrap justify-content-center"%>

app/views/products/show.html.erb
<div style="display: flex; justify-content: center;">  
  <div class="container cart_item" style="width: 50%">
      <div class="row my-4">
        <div class="col-sm-4">
          <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% @product.images.each do |image| %>
                <div class="carousel-item active">
                 <%= image_tag image, size: "300",class: "d-block w-100" %>
                </div>
              <% end %>
            </div>
          </div>
          <%# @product.images.each do |image| %>
            <%#= image_tag image, size: "300" %>
          <%# end %>
        </div>
        <div class="col-sm-8" style="padding: 0 0 0 50px;">
          <%= @product.product_name %>
          <br />
          <%= @product.description%>
          <br />
            ₹<%= @product.discount_price %>
            <s style="color: #9f9191;">₹<%= @product.price%></s>
            <span style= "color: green;">
              <%= @product.discount.discount_amount if @product.discount.present? %> % Off </span>
          <br />
          Delivery Charges: <span style="color: green;">₹ <%= @charges%></span>
          <br/>
          Offers:
          <%@product.offer_types.each do |offer| %>
            <%= offer.name %> discount
            <%= offer.discount_percent %> %
          <% end %>
          <br />
        </div>
      </div>
      <% unless @product.stock == 0 %>
        <div class="row my-4">
          <div class="col-sm-4">
            <%= link_to "AddToCart", new_cart_path(id: @product.id),class: "btn btn-primary btn-lg btn-block" %>
          </div>
          <div class="col-sm-4">
            <%= link_to "Buy Now", new_order_path(id: @product.id, value: 1), method: :get, class: "btn btn-primary btn-lg btn-block"%>
          </div>
        </div>
      <% end %>
  </div>
</div>