config/routes.rb
Rails.application.routes.draw do
	ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
        sessions: 'sessions/sessions',
        registrations: 'sessions/registrations'
      }
  resources :addresses,:bank_accounts, except: [:show]
  resources :carts, only: [:index, :new]
  resources :products, :shipments, only: [:index, :show]
  resources :orders, except: [:edit] do
    get 'detail_pdf', to: 'orders#order_pdf'
  end
  resources :shipments,:tracking_orders, only: [:show]
  resources :seller_signups, only: [:index]
  resources :line_items, :notifications, :otps
  resources :payments

  post "admin/products/add_sub", to: "admin/products#add_sub"
  post "admin/products/variant", to: "admin/products#variant"
  post "admin/products/size_of_product", to: "admin/products#size_of_product"
  root to: "homes#index"
  match '*unmatched', to: 'application#not_found_method', via: :all, constraints: lambda { |req| (req.path.exclude? 'active_storage')}
end

app/views/partials_/_footer.html.erb
<!-- Footer -->
<footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
      <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-facebook-f"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-twitter"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-google"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-instagram"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-linkedin"></i>
      </a>
      <a href="" class="me-4 text-reset">
        <i class="fab fa-github"></i>
      </a>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->

  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold mb-4">
            <i class="fas fa-gem me-3"></i>Company name
          </h6>
          <p>
            Here you can use rows and columns to organize your footer content. Lorem ipsum
            dolor sit amet, consectetur adipisicing elit.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Products
          </h6>
          <p>
            <a href="#!" class="text-reset">Angular</a>
          </p>
          <p>
            <a href="#!" class="text-reset">React</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Vue</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Laravel</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Pricing</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Orders</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
          <p><i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@example.com
          </p>
          <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
          <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>
  <!-- Section: Links  -->

  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

app/views/partials_/_header.html.erb
<%= stylesheet_link_tag "header", "data-turbo-track": "reload" %>
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-nav">
  <div class="container-fluid">
    <% if user_signed_in? %>
      <a class="navbar-brand" href= "/users/edit"><%= image_tag current_user.avatar, size: "45x45" %> </a>
    <% else %>
      <a class="navbar-brand" href="/">E_Commerce</a>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Address", addresses_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Bank Account", bank_accounts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Your Orders", orders_path, class: "nav-link" %>
          </li>
        <% end %>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <%Category.all.each do |category| %>
              <li>
                <%= link_to "#{category.categories_type}", products_path(value: "#{category.categories_type}"), class: "dropdown-item"%>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <% if user_signed_in? %>
        <% if current_user.notification_status %>
          <a id="notify" class= "nav-link button_to text-primary" href="/notifications">
            <i class="fa fa-bell" aria-hidden="true"></i>
          </a>
        <% end %>
        <%= link_to "Cart (#{current_user.cart.line_items.count})", carts_path, class: "nav-link button_to text-primary" %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link button_to" %>
      <% else %>
        <ul style="margin: 0 20px;">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Logins
            </a>
            <ul class="dropdown-menu">
              <%= link_to "Login As Seller", new_otp_path , class: "dropdown-item" %>
              <%= link_to "Login As Buyer/Admin", new_user_session_path, class: "dropdown-item" %>
              <%= link_to " Signup As Buyer", new_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign Up As Seller", new_bank_account_path(value: -2),class: "dropdown-item"%>
            </ul>
          </li>
        </ul>
      <% end %>
      <%= form_tag '/tracking_orders/id', class: "d-flex", method: :get do %>
        <%= text_field_tag :query, "", placeholder: "Search With Track Id",class: "form-control me-2" %>
        <%= button_tag :submit, class: "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
</nav>